'2026-06-11', END='2026-07-19', TZ='America/Mexico_City';
const ESPN_BASE='https://site.api.espn.com/apis/site/v2/sports/soccer/fifa.world/scoreboard';
const FLAG={Mexico:'🇲🇽','South Africa':'🇿🇦','Korea Republic':'🇰🇷','South Korea':'🇰🇷',Czechia:'🇨🇿',Brazil:'🇧🇷',Belgium:'🇧🇪',Argentina:'🇦🇷',France:'🇫🇷',Germany:'🇩🇪',Spain:'🇪🇸',Portugal:'🇵🇹',England:'🏴',USA:'🇺🇸',Canada:'🇨🇦',Japan:'🇯🇵',Morocco:'🇲🇦',Uruguay:'🇺🇾',Colombia:'🇨🇴',Uzbekistan:'🇺🇿'};
const $=s=>document.querySelector(s); let tab=localStorage.tab||'today'; let DATA=JSON.parse(localStorage.wc26||'{"events":[],"updated":null}');
function dates(){let a=[],d=new Date(START+'T12:00:00Z'),e=new Date(END+'T12:00:00Z');while(d<=e){a.push(d.toISOString().slice(0,10).replaceAll('-',''));d.setUTCDate(d.getUTCDate()+1)}return a}
function flag(n){return FLAG[n]||''} function dt(s){return new Date(s)} function fmt(s){return new Intl.DateTimeFormat('es-MX',{timeZone:TZ,day:'2-digit',month:'short',hour:'numeric',minute:'2-digit'}).format(dt(s))}
function dayKey(s){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(dt(s))}
function todayKey(){return new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date())}
function normEvent(e){const comp=e.competitions?.[0]||{}; const cs=comp.competitors||[]; const h=cs.find(x=>x.homeAway==='home')||cs[0]||{}; const a=cs.find(x=>x.homeAway==='away')||cs[1]||{}; const pick=x=>({name:x.team?.displayName||x.team?.shortDisplayName||'Por definir',abbr:x.team?.abbreviation||'',score:x.score===''||x.score==null?null:+x.score,winner:!!x.winner}); const venue=comp.venue||{}; const detail=comp.status?.type?.description||e.status?.type?.description||''; return {id:e.id,date:e.date,stage:e.season?.slug||e.group?.name||e.name||'',group:e.group?.name||e.competitions?.[0]?.notes?.[0]?.headline||'',name:e.name||'',short:e.shortName||'',home:pick(h),away:pick(a),venue:venue.fullName||venue.displayName||'',city:venue.address?.city||'',country:venue.address?.country||'',status:detail,completed:comp.status?.type?.completed||false,odds:[],scorers:[],cards:[],stats:[]}}
async function fetchUrl(url){try{let r=await fetch(url); if(!r.ok) throw new Error(r.status); return await r.json()}catch(e){let proxy='https://api.allorigins.win/raw?url='+encodeURIComponent(url); let r=await fetch(proxy); if(!r.ok) throw new Error('No se pudo consultar fuente'); return await r.json()}}
async function refresh(){ $('#app').innerHTML='<div class="card empty">Consultando partidos reales... Si ESPN/FIFA no libera datos, aparecerá vacío sin inventar resultados.</div>'; let all=[]; for(const d of dates()){try{let j=await fetchUrl(`${ESPN_BASE}?dates=${d}&limit=200`); (j.events||[]).forEach(ev=>all.push(normEvent(ev)))}catch(e){console.log('date fail',d,e.message)}} DATA={events:dedupe(all),updated:new Date().toISOString()}; localStorage.wc26=JSON.stringify(DATA); render()}
function dedupe(arr){let m=new Map();arr.forEach(x=>m.set(x.id||x.date+x.short,x));return [...m.values()].sort((a,b)=>dt(a.date)-dt(b.date))}
function demo(){DATA={updated:new Date().toISOString(),events:[{id:'1',date:new Date().toISOString(),group:'Group A',home:{name:'Mexico',score:2},away:{name:'South Africa',score:0},venue:'Mexico City Stadium',city:'CDMX',country:'Mexico',status:'Final',completed:true,scorers:['Mexico: Giménez 18\'','Mexico: Álvarez 71\''],cards:['South Africa: Mokoena 44\''],stats:['Tiros: 14-7','Posesión: 56%-44%']},{id:'2',date:'2026-06-12T19:00:00Z',group:'Group A',home:{name:'South Korea',score:null},away:{name:'Czechia',score:null},venue:'Guadalajara Stadium',city:'Guadalajara',country:'Mexico',status:'Programado',completed:false,scorers:[],cards:[],stats:[]},{id:'3',date:'2026-06-13T22:00:00Z',group:'Group B',home:{name:'Brazil',score:null},away:{name:'Belgium',score:null},venue:'MetLife Stadium',city:'New York/New Jersey',country:'USA',status:'Programado',completed:false,scorers:[],cards:[],stats:[]}]} ; localStorage.wc26=JSON.stringify(DATA); render()}
function render(){localStorage.tab=tab; document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('on',b.dataset.tab===tab)); if(tab==='today') return renderToday(); if(tab==='calendar') return renderCalendar(); if(tab==='groups') return renderGroups(); if(tab==='bracket') return renderBracket(); renderStats()}
function top(){return `<div class="mut small">Actualizado: ${DATA.updated?fmt(DATA.updated):'sin actualizar'} · Fuente: ESPN/FIFA vía web cuando esté disponible · Hora CDMX</div>`}
function matchCard(m){let score=(m.home.score==null||m.away.score==null)?'vs':`${m.home.score} - ${m.away.score}`; return `<div class="match"><div class="teams"><span>${flag(m.home.name)} ${m.home.name}</span><span class="score">${score}</span><span class="right">${flag(m.away.name)} ${m.away.name}</span></div><div class="meta">🕒 ${fmt(m.date)} · 🏟️ ${m.venue||'Estadio por confirmar'} · 📍 ${[m.city,m.country].filter(Boolean).join(', ')||'Ciudad por confirmar'} · ${m.status||''}</div>${m.scorers?.length?`<ul class="list">${m.scorers.map(x=>`<li>⚽ ${x}</li>`).join('')}</ul>`:''}${m.cards?.length?`<ul class="list">${m.cards.map(x=>`<li>🟨 ${x}</li>`).join('')}</ul>`:''}${m.stats?.length?`<div class="meta">📊 ${m.stats.join(' · ')}</div>`:''}</div>`}
function renderToday(){let k=todayKey(), todays=DATA.events.filter(e=>dayKey(e.date)===k); let tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);let tk=new Intl.DateTimeFormat('en-CA',{timeZone:TZ,year:'numeric',month:'2-digit',day:'2-digit'}).format(tomorrow); let tom=DATA.events.filter(e=>dayKey(e.date)===tk); $('#app').innerHTML=`<div class="grid two"><div class="card"><div class="title">Partidos de hoy</div>${top()}${todays.length?todays.map(matchCard).join(''):'<div class="empty">No hay partidos cargados para hoy. Pulsa Actualizar datos.</div>'}</div><div class="card"><div class="title">Mañana</div>${tom.length?tom.map(matchCard).join(''):'<div class="empty">Sin partidos próximos cargados.</div>'}</div></div>`}
function renderCalendar(){let by={}; DATA.events.forEach(e=>(by[dayKey(e.date)]??=[]).push(e)); let html=Object.keys(by).sort().map(d=>`<div class="card"><div class="title">${new Intl.DateTimeFormat('es-MX',{timeZone:TZ,dateStyle:'full'}).format(new Date(d+'T12:00:00'))}</div>${by[d].map(matchCard).join('')}</div>`).join(''); $('#app').innerHTML=html||'<div class="card empty">Actualiza para cargar calendario por día, horarios CDMX y ciudades.</div>'}
function groupTables(){let teams={}; DATA.events.filter(e=>e.completed&&e.home.score!=null&&e.away.score!=null).forEach(e=>{let g=e.group||'Grupo'; [e.home,e.away].forEach(t=>{let k=g+'|'+t.name; teams[k]??={group:g,name:t.name,p:0,w:0,d:0,l:0,gf:0,ga:0,gd:0,pts:0};}); let H=teams[g+'|'+e.home.name], A=teams[g+'|'+e.away.name]; H.p++;A.p++;H.gf+=e.home.score;H.ga+=e.away.score;A.gf+=e.away.score;A.ga+=e.home.score;H.gd=H.gf-H.ga;A.gd=A.gf-A.ga; if(e.home.score>e.away.score){H.w++;A.l++;H.pts+=3}else if(e.home.score<e.away.score){A.w++;H.l++;A.pts+=3}else{H.d++;A.d++;H.pts++;A.pts++}}); let by={}; Object.values(teams).forEach(t=>(by[t.group]??=[]).push(t)); Object.values(by).forEach(arr=>arr.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf||a.name.localeCompare(b.name))); return by}
function renderGroups(){let by=groupTables(); let html=Object.keys(by).sort().map(g=>`<div class="card"><div class="title">${g}</div><table class="tbl"><tr><th>Equipo</th><th>Pts</th><th>PJ</th><th>DG</th><th>GF</th></tr>${by[g].map((t,i)=>`<tr><td>${i<2?'✅':i===2?'🟡':''} ${flag(t.name)} ${t.name}</td><td class="num">${t.pts}</td><td class="num">${t.p}</td><td class="num">${t.gd}</td><td class="num">${t.gf}</td></tr>`).join('')}</table></div>`).join(''); $('#app').innerHTML=html||'<div class="card empty">Las tablas aparecerán cuando haya resultados finales cargados.</div>'}
function renderBracket(){let by=groupTables(); let winners=[],seconds=[],thirds=[]; Object.keys(by).forEach(g=>{if(by[g][0])winners.push(by[g][0]); if(by[g][1])seconds.push(by[g][1]); if(by[g][2])thirds.push(by[g][2])}); thirds.sort((a,b)=>b.pts-a.pts||b.gd-a.gd||b.gf-a.gf); let best=thirds.slice(0,8); $('#app').innerHTML=`<div class="grid two"><div class="card"><div class="title">Clasificados provisionales</div><div class="meta">Regla 2026: pasan 1.º y 2.º de cada grupo + 8 mejores terceros. Los criterios calculados aquí: puntos, diferencia, goles a favor. Fair play/ranking se dejan como desempate manual.</div><div class="title">Mejores terceros</div>${best.length?best.map((t,i)=>`<div class="krow"><span>${i+1}. ${flag(t.name)} ${t.name} <span class="mut">${t.group}</span></span><b>${t.pts} pts</b></div>`).join(''):'<div class="empty">Aún no hay terceros calculables.</div>'}</div><div class="card"><div class="title">Llaves 16vos</div><div class="meta">Se llenan conforme FIFA/ESPN confirme cruces oficiales. La app mantiene el cálculo de clasificados; los cruces exactos con terceros se deben sincronizar con la matriz oficial publicada.</div><div class="bracket"><div class="slot">1A vs 3C/E/F/H/I</div><div class="slot">1B vs 3E/F/G/I/J</div><div class="slot">1C vs 3A/B/F/H/I</div><div class="slot">1D vs 3B/E/F/I/J</div></div></div></div>`}
function renderStats(){let scorers={},cards={}; DATA.events.forEach(e=>{(e.scorers||[]).forEach(s=>{let n=s.replace(/.*?:/,'').replace(/\d+'.*/,'').trim(); if(n)scorers[n]=(scorers[n]||0)+1});(e.cards||[]).forEach(s=>{let n=s.replace(/.*?:/,'').replace(/\d+'.*/,'').trim(); if(n)cards[n]=(cards[n]||0)+1})}); const list=o=>Object.entries(o).sort((a,b)=>b[1]-a[1]).slice(0,20).map(([n,v],i)=>`<div class="krow"><span>${i+1}. ${n}</span><b>${v}</b></div>`).join('')||'<div class="empty">Sin datos todavía.</div>'; $('#app').innerHTML=`<div class="grid two"><div class="card"><div class="title">Goleadores</div>${list(scorers)}</div><div class="card"><div class="title">Tarjetas</div>${list(cards)}</div></div>`}
function byText(txt){
  return [...document.querySelectorAll('button')].find(b=>b.textContent.trim().toLowerCase().includes(txt));
}

const btnRefresh = document.querySelector('#refresh') || byText('actualizar');
const btnDemo = document.querySelector('#demo') || byText('ejemplo');
const btnClear = document.querySelector('#clear') || byText('limpiar');

if(btnRefresh) btnRefresh.onclick = refresh;
if(btnDemo) btnDemo.onclick = demo;
if(btnClear) btnClear.onclick = () => {
  localStorage.removeItem('wc26');
  DATA = {events:[], updated:null};
  render();
};

document.querySelectorAll('[data-tab]').forEach(b=>{
  b.onclick = () => {
    tab = b.dataset.tab;
    render();
  };
});

render();
